title: LaTex Cheatsheet
markdown: kramdown

# for atom feed
author:
  name: Brage Wiseth

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
